-- Asiimov, from skills/primer/references/design.md: cream paper, neutral
-- ink, one orange accent (ember), moss green. Same palette as the Obsidian theme
-- in obsidian/themes/Asiimov and ghostty/themes/asiimov-{light,dark}.
--
-- One file for both modes: it reads 'background' instead of setting it, and
-- Neovim re-sources the active colorscheme whenever 'background' changes.
--
-- Syntax follows the design's four code classes: keywords in ember-text,
-- literals in moss, comments in ink-muted, everything else in ink. Colors the
-- design does not define (red, blue, diff tints) are muted warm picks, with the
-- tints pre-blended over the paper.

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end
vim.o.termguicolors = true
vim.g.colors_name = "asiimov"

local palettes = {
    light = {
        paper = "#f8f6f1",
        paper_raised = "#fdfcfa",
        paper_sunken = "#efece4",
        line = "#e2ddd2",
        ink = "#1c1b18",
        ink_muted = "#66635c",
        ink_faint = "#9a968d",
        ember = "#fc6603",
        ember_text = "#b54600",
        ember_soft = "#ffe6d4",
        moss = "#3d6b3a",
        red = "#a8322a",
        blue = "#2f5d8a",

        diff_add = "#e2e5db",
        diff_add_text = "#c9d3c3",
        diff_del = "#eedfd9",
        diff_del_text = "#e4c5bf",
        diff_change = "#ffe6d4",
        diff_change_text = "#f9d2b6",

        ansi = {
            "#1c1b18", "#a8322a", "#3d6b3a", "#b54600",
            "#2f5d8a", "#7d4a8a", "#2e6f73", "#66635c",
            "#8a867d", "#c4372c", "#4f8a4a", "#fc6603",
            "#3a72a8", "#955aa3", "#358589", "#b8b3a8",
        },
    },
    dark = {
        paper = "#24231f",
        paper_raised = "#2d2c28",
        paper_sunken = "#1c1b18",
        line = "#44423c",
        ink = "#f2efe8",
        ink_muted = "#aaa69c",
        ink_faint = "#7d7a71",
        ember = "#fc6603",
        ember_text = "#ff9a4d",
        ember_soft = "#442d1a",
        moss = "#8fc48a",
        red = "#e5736a",
        blue = "#7fa7d4",

        diff_add = "#31362c",
        diff_add_text = "#3f4b3a",
        diff_del = "#3b2d28",
        diff_del_text = "#543732",
        diff_change = "#442d1a",
        diff_change_text = "#5a3418",

        ansi = {
            "#44423c", "#e5736a", "#8fc48a", "#ff9a4d",
            "#7fa7d4", "#c29ad0", "#7fbfbf", "#d8d4ca",
            "#7d7a71", "#f08c84", "#a8d6a3", "#ffb070",
            "#9dbde3", "#d4b3df", "#9dd3d3", "#f2efe8",
        },
    },
}

local c = palettes[vim.o.background] or palettes.dark

for i, hex in ipairs(c.ansi) do
    vim.g["terminal_color_" .. (i - 1)] = hex
end

local groups = {
    -- base UI: paper for the editor, sunken for bars, raised for floats
    Normal = { fg = c.ink, bg = c.paper },
    NormalNC = { fg = c.ink, bg = c.paper },
    NormalFloat = { fg = c.ink, bg = c.paper_raised },
    FloatBorder = { fg = c.line, bg = c.paper_raised },
    FloatTitle = { fg = c.ink, bg = c.paper_raised },
    ColorColumn = { bg = c.paper_sunken },
    Conceal = { fg = c.ink_muted },
    Cursor = { fg = c.paper, bg = c.ember },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = c.paper_sunken },
    CursorColumn = { bg = c.paper_sunken },
    CursorLineNr = { fg = c.ink },
    LineNr = { fg = c.ink_faint },
    LineNrAbove = { fg = c.ink_faint },
    LineNrBelow = { fg = c.ink_faint },
    SignColumn = { bg = c.paper },
    FoldColumn = { fg = c.ink_faint, bg = c.paper },
    Folded = { fg = c.ink_muted, bg = c.paper_sunken },
    Directory = { fg = c.ink },
    EndOfBuffer = { fg = c.paper },
    NonText = { fg = c.line },
    SpecialKey = { fg = c.ink_faint },
    Whitespace = { fg = c.line },
    VertSplit = { fg = c.line },
    WinSeparator = { fg = c.line },
    MatchParen = { bg = c.line, bold = true },
    Visual = { bg = c.line },
    VisualNOS = { bg = c.line },
    Search = { bg = c.ember_soft },
    IncSearch = { fg = c.paper, bg = c.ember },
    CurSearch = { link = "IncSearch" },
    Substitute = { link = "IncSearch" },
    Title = { fg = c.ink, bold = true },
    Question = { fg = c.ink },
    MoreMsg = { fg = c.moss },
    ModeMsg = { fg = c.ink },
    ErrorMsg = { fg = c.red },
    WarningMsg = { fg = c.ember_text },
    QuickFixLine = { bg = c.line },
    SpellBad = { sp = c.red, undercurl = true },
    SpellCap = { sp = c.ember_text, undercurl = true },
    SpellLocal = { sp = c.blue, undercurl = true },
    SpellRare = { sp = c.ink_muted, undercurl = true },

    StatusLine = { fg = c.ink_muted, bg = c.paper_sunken },
    StatusLineNC = { fg = c.ink_faint, bg = c.paper_sunken },
    WinBar = { fg = c.ink_muted, bg = c.paper },
    WinBarNC = { fg = c.ink_faint, bg = c.paper },
    TabLine = { fg = c.ink_muted, bg = c.paper_sunken },
    TabLineFill = { bg = c.paper_sunken },
    TabLineSel = { fg = c.ink, bg = c.paper },

    Pmenu = { fg = c.ink, bg = c.paper_raised },
    PmenuSel = { bg = c.line },
    PmenuSbar = { bg = c.paper_raised },
    PmenuThumb = { bg = c.ink_faint },
    PmenuMatch = { fg = c.ember_text, bold = true },
    PmenuMatchSel = { fg = c.ember_text, bg = c.line, bold = true },
    WildMenu = { link = "PmenuSel" },

    -- legacy syntax groups
    Comment = { fg = c.ink_muted },
    Constant = { fg = c.moss },
    String = { fg = c.moss },
    Character = { fg = c.moss },
    Number = { fg = c.moss },
    Boolean = { fg = c.moss },
    Float = { fg = c.moss },
    Identifier = { fg = c.ink },
    Function = { fg = c.ink },
    Statement = { fg = c.ember_text },
    Conditional = { fg = c.ember_text },
    Repeat = { fg = c.ember_text },
    Label = { fg = c.ember_text },
    Operator = { fg = c.ink_muted },
    Keyword = { fg = c.ember_text },
    Exception = { fg = c.ember_text },
    PreProc = { fg = c.ember_text },
    Include = { fg = c.ember_text },
    Define = { fg = c.ember_text },
    Macro = { fg = c.ink },
    PreCondit = { fg = c.ember_text },
    Type = { fg = c.ink },
    StorageClass = { fg = c.ember_text },
    Structure = { fg = c.ink },
    Typedef = { fg = c.ink },
    Special = { fg = c.ink },
    SpecialChar = { fg = c.moss },
    Tag = { fg = c.ink },
    Delimiter = { fg = c.ink_muted },
    SpecialComment = { fg = c.ink_muted },
    Debug = { fg = c.ember_text },
    Underlined = { fg = c.ember_text, underline = true },
    Ignore = { fg = c.ink_faint },
    Error = { fg = c.red },
    Todo = { fg = c.paper, bg = c.ember, bold = true },

    -- diff
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_del },
    DiffText = { bg = c.diff_change_text },
    diffAdded = { fg = c.moss },
    diffRemoved = { fg = c.red },
    diffChanged = { fg = c.ember_text },
    diffFile = { fg = c.ink },
    diffLine = { fg = c.ink_muted, bold = true },

    -- diagnostics
    DiagnosticError = { fg = c.red },
    DiagnosticWarn = { fg = c.ember_text },
    DiagnosticInfo = { fg = c.blue },
    DiagnosticHint = { fg = c.ink_muted },
    DiagnosticOk = { fg = c.moss },
    DiagnosticUnderlineError = { sp = c.red, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.ember_text, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.blue, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.ink_muted, undercurl = true },
    DiagnosticUnderlineOk = { sp = c.moss, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.red },
    DiagnosticVirtualTextWarn = { fg = c.ember_text },
    DiagnosticVirtualTextInfo = { fg = c.blue },
    DiagnosticVirtualTextHint = { fg = c.ink_muted },
    DiagnosticUnnecessary = { fg = c.ink_faint },
    DiagnosticDeprecated = { fg = c.ink_faint, strikethrough = true },

    -- LSP
    LspReferenceText = { bg = c.line },
    LspReferenceRead = { bg = c.line },
    LspReferenceWrite = { bg = c.line, underline = true },
    LspSignatureActiveParameter = { fg = c.ember_text, bold = true },
    LspInlayHint = { fg = c.ink_faint },
    LspCodeLens = { fg = c.ink_faint },

    -- treesitter
    ["@comment"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.red },
    ["@comment.warning"] = { fg = c.ember_text },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { fg = c.blue },
    ["@constant"] = { fg = c.ink },
    ["@constant.builtin"] = { fg = c.moss },
    ["@constant.macro"] = { fg = c.ink },
    ["@string"] = { fg = c.moss },
    ["@string.escape"] = { fg = c.moss, bold = true },
    ["@string.regexp"] = { fg = c.moss },
    ["@string.special"] = { fg = c.moss },
    ["@string.special.url"] = { fg = c.ember_text, underline = true },
    ["@character"] = { fg = c.moss },
    ["@character.special"] = { fg = c.moss },
    ["@number"] = { fg = c.moss },
    ["@boolean"] = { fg = c.moss },
    ["@float"] = { fg = c.moss },
    ["@function"] = { fg = c.ink },
    ["@function.builtin"] = { fg = c.ink },
    ["@function.call"] = { fg = c.ink },
    ["@function.macro"] = { fg = c.ink },
    ["@function.method"] = { fg = c.ink },
    ["@function.method.call"] = { fg = c.ink },
    ["@constructor"] = { fg = c.ink },
    ["@parameter"] = { fg = c.ink },
    ["@variable.parameter"] = { fg = c.ink },
    ["@keyword"] = { fg = c.ember_text },
    ["@keyword.function"] = { fg = c.ember_text },
    ["@keyword.operator"] = { fg = c.ember_text },
    ["@keyword.return"] = { fg = c.ember_text },
    ["@keyword.import"] = { fg = c.ember_text },
    ["@keyword.exception"] = { fg = c.ember_text },
    ["@keyword.conditional"] = { fg = c.ember_text },
    ["@keyword.repeat"] = { fg = c.ember_text },
    ["@keyword.directive"] = { fg = c.ember_text },
    ["@operator"] = { fg = c.ink_muted },
    ["@punctuation.delimiter"] = { fg = c.ink_muted },
    ["@punctuation.bracket"] = { fg = c.ink_muted },
    ["@punctuation.special"] = { fg = c.ink_muted },
    ["@type"] = { fg = c.ink },
    ["@type.builtin"] = { fg = c.ink },
    ["@type.definition"] = { fg = c.ink },
    ["@type.qualifier"] = { fg = c.ember_text },
    ["@attribute"] = { fg = c.ink_muted },
    ["@property"] = { fg = c.ink },
    ["@field"] = { fg = c.ink },
    ["@variable"] = { fg = c.ink },
    ["@variable.builtin"] = { fg = c.ember_text },
    ["@variable.member"] = { fg = c.ink },
    ["@module"] = { fg = c.ink },
    ["@namespace"] = { fg = c.ink },
    ["@label"] = { fg = c.ember_text },
    ["@tag"] = { fg = c.ember_text },
    ["@tag.builtin"] = { fg = c.ember_text },
    ["@tag.attribute"] = { fg = c.ink },
    ["@tag.delimiter"] = { fg = c.ink_muted },

    -- markdown
    ["@markup.heading"] = { fg = c.ink, bold = true },
    ["@markup.strong"] = { fg = c.ink, bold = true },
    ["@markup.italic"] = { fg = c.ink, italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.raw"] = { fg = c.moss },
    ["@markup.link"] = { fg = c.ember_text },
    ["@markup.link.url"] = { fg = c.ember_text, underline = true },
    ["@markup.link.label"] = { fg = c.ember_text },
    ["@markup.list"] = { fg = c.ink_muted },
    ["@markup.quote"] = { fg = c.ink_muted, italic = true },
    ["@diff.plus"] = { fg = c.moss },
    ["@diff.minus"] = { fg = c.red },
    ["@diff.delta"] = { fg = c.ember_text },

    -- LSP semantic tokens
    ["@lsp.type.class"] = { fg = c.ink },
    ["@lsp.type.decorator"] = { fg = c.ink_muted },
    ["@lsp.type.enum"] = { fg = c.ink },
    ["@lsp.type.enumMember"] = { fg = c.ink },
    ["@lsp.type.function"] = { fg = c.ink },
    ["@lsp.type.interface"] = { fg = c.ink },
    ["@lsp.type.macro"] = { fg = c.ink },
    ["@lsp.type.method"] = { fg = c.ink },
    ["@lsp.type.namespace"] = { fg = c.ink },
    ["@lsp.type.parameter"] = { fg = c.ink },
    ["@lsp.type.property"] = { fg = c.ink },
    ["@lsp.type.struct"] = { fg = c.ink },
    ["@lsp.type.type"] = { fg = c.ink },
    ["@lsp.type.typeParameter"] = { fg = c.ink },
    ["@lsp.type.variable"] = { fg = c.ink },
    ["@lsp.mod.readonly"] = { fg = c.ink },
    ["@lsp.typemod.variable.readonly"] = { fg = c.ink },

    -- gitsigns
    GitSignsAdd = { fg = c.moss },
    GitSignsChange = { fg = c.ember_text },
    GitSignsDelete = { fg = c.red },
    GitSignsAddLn = { bg = c.diff_add },
    GitSignsChangeLn = { bg = c.diff_change },
    GitSignsDeleteLn = { bg = c.diff_del },
    GitSignsCurrentLineBlame = { fg = c.ink_faint },

    -- athena (PR review). Sits above gitsigns in the signcolumn, so both the
    -- PR diff and your uncommitted changes are visible at once.
    AthenaAdd = { fg = c.moss },
    AthenaChange = { fg = c.ember_text },
    AthenaDelete = { fg = c.red },
    AthenaAddLn = { bg = c.diff_add },
    AthenaChangeLn = { bg = c.diff_change },
    -- the cursor line needs to stay visible on top of a tinted line
    AthenaAddCul = { bg = c.diff_add_text },
    AthenaChangeCul = { bg = c.diff_change_text },
    AthenaThread = { fg = c.blue },
    AthenaThreadResolved = { fg = c.ink_faint },
    AthenaThreadHeader = { fg = c.ink, bold = true },
    AthenaThreadBody = { fg = c.ink },
    AthenaThreadPending = { fg = c.ember_text },
    AthenaSidebarDir = { fg = c.ink_faint },
    AthenaSidebarAdd = { fg = c.moss },
    AthenaSidebarDel = { fg = c.red },
    AthenaSidebarViewed = { fg = c.ink_faint },
    AthenaSidebarUnviewed = { fg = c.ember_text },

    -- telescope
    TelescopeNormal = { fg = c.ink, bg = c.paper_raised },
    TelescopeBorder = { fg = c.line, bg = c.paper_raised },
    TelescopeTitle = { fg = c.ink_muted },
    TelescopePromptNormal = { fg = c.ink, bg = c.paper_raised },
    TelescopePromptBorder = { fg = c.line, bg = c.paper_raised },
    TelescopePromptPrefix = { fg = c.ember },
    TelescopeSelection = { fg = c.ink, bg = c.line },
    TelescopeMatching = { fg = c.ember_text, bold = true },

    -- snacks / lazy / mason / which-key
    SnacksNormal = { fg = c.ink, bg = c.paper_raised },
    SnacksWinBar = { fg = c.ink, bg = c.paper_raised },
    SnacksBackdrop = { bg = c.paper_sunken },
    SnacksDashboardHeader = { fg = c.ember },
    SnacksDashboardIcon = { fg = c.ink_muted },
    SnacksDashboardDesc = { fg = c.ink },
    SnacksDashboardKey = { fg = c.ember_text },
    SnacksDashboardFooter = { fg = c.ink_muted },
    SnacksIndent = { fg = c.line },
    SnacksIndentScope = { fg = c.ink_faint },
    SnacksPickerDir = { fg = c.ink_muted },
    SnacksPickerMatch = { fg = c.ember_text, bold = true },
    LazyNormal = { fg = c.ink, bg = c.paper_raised },
    MasonNormal = { fg = c.ink, bg = c.paper_raised },
    WhichKey = { fg = c.ember_text },
    WhichKeyGroup = { fg = c.ink },
    WhichKeyDesc = { fg = c.ink },
    WhichKeySeparator = { fg = c.ink_faint },
    WhichKeyNormal = { fg = c.ink, bg = c.paper_raised },

    -- treesitter-context, illuminate, rainbow-delimiters
    TreesitterContext = { bg = c.paper_sunken },
    TreesitterContextLineNumber = { fg = c.ink_faint, bg = c.paper_sunken },
    IlluminatedWordText = { bg = c.line },
    IlluminatedWordRead = { bg = c.line },
    IlluminatedWordWrite = { bg = c.line, underline = true },
    RainbowDelimiterYellow = { fg = c.ansi[12] },
    RainbowDelimiterViolet = { fg = c.ansi[6] },
    RainbowDelimiterBlue = { fg = c.ansi[5] },
    RainbowDelimiterOrange = { fg = c.ember_text },
    RainbowDelimiterGreen = { fg = c.ansi[3] },
    RainbowDelimiterRed = { fg = c.ansi[2] },
    RainbowDelimiterCyan = { fg = c.ansi[7] },
}

for name, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, name, spec)
end
